---
name: PAD
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - prophet==1.1.2
  - pip:
      - certifi
      - pandas
      - schedule
      - prometheus_client
      - prometheus-api-client
      - tornado
      - dateparser
      - mlflow
      - numpy
      - holidays
      - tensorflow
      - scikit-learn
      - statsmodels
